#!/bin/sh
set -e

if command -v systemctl >/dev/null 2>&1; then
  systemctl stop realms.service >/dev/null 2>&1 || true
  systemctl disable realms.service >/dev/null 2>&1 || true
  systemctl daemon-reload >/dev/null 2>&1 || true
fi

exit 0
