name: "✨ Feature 请求"
description: 提议新功能或体验改进（含 API / Web / 管理后台 / 文档）
title: "[Feature]: "
labels:
  - enhancement
  - needs-triage
body:
  - type: markdown
    attributes:
      value: |
        感谢你的想法！

        参考 Kubernetes、React、Rust 等项目的实践，我们更偏好：
        - 先说清楚要解决的**具体问题**
        - 再给出可执行的**方案与验收标准**

  - type: checkboxes
    id: precheck
    attributes:
      label: 提交前检查
      options:
        - label: 我已搜索现有 Issues/PR，确认不是重复提案
          required: true
        - label: 我愿意配合补充细节（边界、兼容性、验证方式）
          required: true

  - type: textarea
    id: problem
    attributes:
      label: 背景与问题
      description: 当前痛点是什么？谁会受影响？
      placeholder: 在 XXX 场景下，现有能力无法满足 XXX，导致 XXX
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 期望方案
      description: 描述你希望新增/调整的行为
      placeholder: 希望在 ... 增加 ...，并通过 ... 配置控制
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 备选方案（可选）
      description: 你考虑过哪些替代方案？为什么不采用？

  - type: checkboxes
    id: scope
    attributes:
      label: 影响范围（可多选）
      options:
        - label: API（例如 /v1/* 或 /api/*）
        - label: 管理后台（/admin/*）
        - label: 用户控制台（/dashboard/*）
        - label: 配置/部署（.env、Docker、发布）
        - label: 文档（README/docs/知识库）
        - label: CI/测试

  - type: textarea
    id: compatibility
    attributes:
      label: 兼容性与风险评估
      description: 是否有 breaking change？是否影响默认行为？
      placeholder: 默认保持兼容，仅在开启 XXX 开关后生效

  - type: textarea
    id: acceptance
    attributes:
      label: 验收标准
      description: 这个需求完成后，如何判断“做对了”？
      placeholder: |
        - [ ] 场景 A 能够 ...
        - [ ] 场景 B 不受影响
        - [ ] 文档/测试已补齐
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: 补充信息（可选）
      description: 可附原型、截图、参考链接、相关 PR
