model_provider = "su8codes"
model = "gpt-5.2"
model_reasoning_effort = 'xhigh'
web_search = 'live'

[model_providers.su8codes]
name = "su8codes"
base_url = "https://www.su8.codes/codex/v1"
env_key = "CODEX_API_KEY"
wire_api = "responses"

[features]
view_image_tool = true

[mcp_servers]
[mcp_servers.playwright]
args = ['@playwright/mcp@latest']
command = 'npx'
